In [126]:
import numpy as np
import pandas as pd

In [127]:
df=pd.read_csv('housetrain.csv')
df1=pd.read_csv('test.csv')
df2=pd.read_csv('submission.csv')

In [128]:
df.head()

Property_ID  room layout_type      property_type                 locality  \
0        42208     3         BHK  Independent House               Palavakkam   
1        90879     1         BHK          Apartment                Manikonda   
2        99943     3         BHK          Apartment             Jodhpur Park   
3       113926     1         BHK          Apartment                  Chembur   
4       185438     1         BHK   Studio Apartment  Kalewadi Pandhapur Road   

   price  area    furnish_type  bathroom       city  ...  floor  pet_friendly  \
0  33624  1312       Furnished         2    Chennai  ...      1             1   
1   9655  1474     Unfurnished         2  Hyderabad  ...     17             0   
2  23699  1837  Semi-Furnished         2    Kolkata  ...     10             1   
3   6306   606     Unfurnished         1     Mumbai  ...     18             0   
4  12008   498  Semi-Furnished         3       Pune  ...     14             0   

   power_backup  washing_machine  air_conditioner  geyser/solar  \
0             0                0                1             0   
1             1                0                0             1   
2             1                1                1             0   
3             0                0                0             0   
4             0                1                1             0   

   security_deposit  CCTV/security  lift  neighbourhood  
0            302616              0     0            300  
1             19310              0     1           1600  
2            118495              0     1           3100  
3             37836              0     1            300  
4             72048              0     1              0  

[5 rows x 21 columns]

In [129]:
df1.head()

Property_ID  room layout_type      property_type         locality  area  \
0       114342     2         BHK  Independent Floor           Palava  1347   
1        88819     1         BHK  Independent House       Somajiguda   634   
2        85623     1         BHK          Apartment      Toli Chowki   524   
3       130856     3         BHK          Apartment       Thane West  1837   
4        40089     2         BHK          Apartment  Krishnarajapura  1208   

     furnish_type  bathroom       city  parking_spaces  ...  pet_friendly  \
0  Semi-Furnished         1     Mumbai               0  ...             0   
1  Semi-Furnished         3  Hyderabad               1  ...             0   
2     Unfurnished         1  Hyderabad               1  ...             1   
3     Unfurnished         5     Mumbai               1  ...             1   
4  Semi-Furnished         2  Bangalore               1  ...             0   

   power_backup  washing_machine  air_conditioner  geyser/solar  \
0             1                1                1             0   
1             0                1                1             0   
2             1                0                0             0   
3             0                0                0             1   
4             1                1                1             0   

   security_deposit  CCTV/security  lift  neighbourhood  price  
0             72624              1     0            900    NaN  
1             19656              0     0           2500    NaN  
2              7500              0     0           3200    NaN  
3            137646              1     1           1200    NaN  
4            110898              0     1           1000    NaN  

[5 rows x 21 columns]

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134683 entries, 0 to 134682
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   Property_ID       134683 non-null  int64 
 1   room              134683 non-null  int64 
 2   layout_type       134683 non-null  object
 3   property_type     134683 non-null  object
 4   locality          134683 non-null  object
 5   price             134683 non-null  int64 
 6   area              134683 non-null  int64 
 7   furnish_type      134683 non-null  object
 8   bathroom          134683 non-null  int64 
 9   city              134683 non-null  object
 10  parking_spaces    134683 non-null  int64 
 11  floor             134683 non-null  int64 
 12  pet_friendly      134683 non-null  int64 
 13  power_backup      134683 non-null  int64 
 14  washing_machine   134683 non-null  int64 
 15  air_conditioner   134683 non-null  int64 
 16  geyser/solar      134683 non-null  int

In [131]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57722 entries, 0 to 57721
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Property_ID       57722 non-null  int64  
 1   room              57722 non-null  int64  
 2   layout_type       57722 non-null  object 
 3   property_type     57722 non-null  object 
 4   locality          57722 non-null  object 
 5   area              57722 non-null  int64  
 6   furnish_type      57722 non-null  object 
 7   bathroom          57722 non-null  int64  
 8   city              57722 non-null  object 
 9   parking_spaces    57722 non-null  int64  
 10  floor             57722 non-null  int64  
 11  pet_friendly      57722 non-null  int64  
 12  power_backup      57722 non-null  int64  
 13  washing_machine   57722 non-null  int64  
 14  air_conditioner   57722 non-null  int64  
 15  geyser/solar      57722 non-null  int64  
 16  security_deposit  57722 non-null  int64 

In [132]:
df.isnull().any()

Property_ID         False
room                False
layout_type         False
property_type       False
locality            False
price               False
area                False
furnish_type        False
bathroom            False
city                False
parking_spaces      False
floor               False
pet_friendly        False
power_backup        False
washing_machine     False
air_conditioner     False
geyser/solar        False
security_deposit    False
CCTV/security       False
lift                False
neighbourhood       False
dtype: bool

In [133]:
df1.isnull().any()

Property_ID         False
room                False
layout_type         False
property_type       False
locality            False
area                False
furnish_type        False
bathroom            False
city                False
parking_spaces      False
floor               False
pet_friendly        False
power_backup        False
washing_machine     False
air_conditioner     False
geyser/solar        False
security_deposit    False
CCTV/security       False
lift                False
neighbourhood       False
price                True
dtype: bool

In [134]:
df.drop(columns=['Property_ID'],inplace=True)

In [135]:
df1.drop(columns=['Property_ID'],inplace=True)

In [136]:
df.drop(columns=['pet_friendly'],inplace=True)

In [137]:
df1.drop(columns=['pet_friendly'],inplace=True)

In [138]:
df.head()

room layout_type      property_type                 locality  price  area  \
0     3         BHK  Independent House               Palavakkam  33624  1312   
1     1         BHK          Apartment                Manikonda   9655  1474   
2     3         BHK          Apartment             Jodhpur Park  23699  1837   
3     1         BHK          Apartment                  Chembur   6306   606   
4     1         BHK   Studio Apartment  Kalewadi Pandhapur Road  12008   498   

     furnish_type  bathroom       city  parking_spaces  floor  power_backup  \
0       Furnished         2    Chennai               1      1             0   
1     Unfurnished         2  Hyderabad               0     17             1   
2  Semi-Furnished         2    Kolkata               0     10             1   
3     Unfurnished         1     Mumbai               0     18             0   
4  Semi-Furnished         3       Pune               0     14             0   

   washing_machine  air_conditioner  geyser/solar  security_deposit  \
0                0                1             0            302616   
1                0                0             1             19310   
2                1                1             0            118495   
3                0                0             0             37836   
4                1                1             0             72048   

   CCTV/security  lift  neighbourhood  
0              0     0            300  
1              0     1           1600  
2              0     1           3100  
3              0     1            300  
4              0     1              0

In [139]:
df['property_type'].unique()

array(['Independent House', 'Apartment', 'Studio Apartment',
       'Independent Floor', 'Villa', 'Penthouse'], dtype=object)

In [140]:
df['furnish_type'].unique()

array(['Furnished', 'Unfurnished', 'Semi-Furnished'], dtype=object)

In [141]:
df['city'].unique()

array(['Chennai', 'Hyderabad', 'Kolkata', 'Mumbai', 'Pune', 'Delhi',
       'Bangalore', 'Ahmedabad'], dtype=object)

In [142]:
df['layout_type'].unique()

array(['BHK', 'RK'], dtype=object)

In [143]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df.layout_type=le.fit_transform(df.layout_type)
df.city=le.fit_transform(df.city)
df.furnish_type=le.fit_transform(df.furnish_type)
df.property_type=le.fit_transform(df.property_type)

In [144]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df1.layout_type=le.fit_transform(df1.layout_type)
df1.city=le.fit_transform(df1.city)
df1.furnish_type=le.fit_transform(df1.furnish_type)
df1.property_type=le.fit_transform(df1.property_type)

In [145]:
df.head()

room  layout_type  property_type                 locality  price  area  \
0     3            0              2               Palavakkam  33624  1312   
1     1            0              0                Manikonda   9655  1474   
2     3            0              0             Jodhpur Park  23699  1837   
3     1            0              0                  Chembur   6306   606   
4     1            0              4  Kalewadi Pandhapur Road  12008   498   

   furnish_type  bathroom  city  parking_spaces  floor  power_backup  \
0             0         2     2               1      1             0   
1             2         2     4               0     17             1   
2             1         2     5               0     10             1   
3             2         1     6               0     18             0   
4             1         3     7               0     14             0   

   washing_machine  air_conditioner  geyser/solar  security_deposit  \
0                0                1             0            302616   
1                0                0             1             19310   
2                1                1             0            118495   
3                0                0             0             37836   
4                1                1             0             72048   

   CCTV/security  lift  neighbourhood  
0              0     0            300  
1              0     1           1600  
2              0     1           3100  
3              0     1            300  
4              0     1              0

In [146]:
df.drop(columns=['locality'],inplace=True)

In [147]:
df1.drop(columns=['locality'],inplace=True)

In [148]:
df.head()

room  layout_type  property_type  price  area  furnish_type  bathroom  \
0     3            0              2  33624  1312             0         2   
1     1            0              0   9655  1474             2         2   
2     3            0              0  23699  1837             1         2   
3     1            0              0   6306   606             2         1   
4     1            0              4  12008   498             1         3   

   city  parking_spaces  floor  power_backup  washing_machine  \
0     2               1      1             0                0   
1     4               0     17             1                0   
2     5               0     10             1                1   
3     6               0     18             0                0   
4     7               0     14             0                1   

   air_conditioner  geyser/solar  security_deposit  CCTV/security  lift  \
0                1             0            302616              0     0   
1                0             1             19310              0     1   
2                1             0            118495              0     1   
3                0             0             37836              0     1   
4                1             0             72048              0     1   

   neighbourhood  
0            300  
1           1600  
2           3100  
3            300  
4              0

In [149]:
df[['room','layout_type','property_type','area','furnish_type','bathroom','city','parking_spaces','floor','power_backup','washing_machine','air_conditioner','geyser/solar','security_deposit','CCTV/security','lift','neighbourhood','price']]

room  layout_type  property_type  area  furnish_type  bathroom  city  \
0          3            0              2  1312             0         2     2   
1          1            0              0  1474             2         2     4   
2          3            0              0  1837             1         2     5   
3          1            0              0   606             2         1     6   
4          1            0              4   498             1         3     7   
...      ...          ...            ...   ...           ...       ...   ...   
134678     3            0              1   641             2         1     6   
134679     1            0              1   619             2         2     7   
134680     3            0              0  2279             1         3     6   
134681     1            0              0  1314             2         2     7   
134682     1            1              1   798             1         2     2   

        parking_spaces  floor  power_backup  washing_machine  air_conditioner  \
0                    1      1             0                0                1   
1                    0     17             1                0                0   
2                    0     10             1                1                1   
3                    0     18             0                0                0   
4                    0     14             0                1                1   
...                ...    ...           ...              ...              ...   
134678               1     19             0                0                0   
134679               0      2             1                0                0   
134680               1      5             1                1                1   
134681               0     14             1                0                0   
134682               0      8             0                1                1   

        geyser/solar  security_deposit  CCTV/security  lift  neighbourhood  \
0                  0            302616              0     0            300   
1                  1             19310              0     1           1600   
2                  0            118495              0     1           3100   
3                  0             37836              0     1            300   
4                  0             72048              0     1              0   
...              ...               ...            ...   ...            ...   
134678             1           1783896              1     1           3900   
134679             1             62622              0     0           1200   
134680             0            429060              0     0           3900   
134681             0             79595              0     1           2300   
134682             1             74042              0     1           3600   

         price  
0        33624  
1         9655  
2        23699  
3         6306  
4        12008  
...        ...  
134678  222987  
134679    6958  
134680   85812  
134681   15919  
134682   37021  

[134683 rows x 18 columns]

In [150]:
df1
[['room','layout_type','property_type','area','furnish_type','bathroom','city','parking_spaces','floor','power_backup','washing_machine','air_conditioner','geyser/solar','security_deposit','CCTV/security','lift','neighbourhood','price']]

[['room',
  'layout_type',
  'property_type',
  'area',
  'furnish_type',
  'bathroom',
  'city',
  'parking_spaces',
  'floor',
  'power_backup',
  'washing_machine',
  'air_conditioner',
  'geyser/solar',
  'security_deposit',
  'CCTV/security',
  'lift',
  'neighbourhood',
  'price']]

In [151]:
X=df.iloc[:,:-1].values

In [152]:
y=df.iloc[:,-1]

In [153]:
X

array([[     3,      0,      2, ..., 302616,      0,      0],
       [     1,      0,      0, ...,  19310,      0,      1],
       [     3,      0,      0, ..., 118495,      0,      1],
       ...,
       [     3,      0,      0, ..., 429060,      0,      0],
       [     1,      0,      0, ...,  79595,      0,      1],
       [     1,      1,      1, ...,  74042,      0,      1]], dtype=int64)

In [154]:
y

0          300
1         1600
2         3100
3          300
4            0
          ... 
134678    3900
134679    1200
134680    3900
134681    2300
134682    3600
Name: neighbourhood, Length: 134683, dtype: int64

In [155]:
df1["price"]=0

In [156]:
test_x=df1.iloc[:,:-1].values
test_y = df1["price"]

In [157]:
test_y

0        0
1        0
2        0
3        0
4        0
        ..
57717    0
57718    0
57719    0
57720    0
57721    0
Name: price, Length: 57722, dtype: int64

In [158]:
from sklearn import linear_model

In [159]:
reg=linear_model.LinearRegression()
reg.fit(df[['room','layout_type','property_type','area','furnish_type','bathroom','city','parking_spaces','floor','power_backup','washing_machine','air_conditioner','geyser/solar','security_deposit','CCTV/security','lift','neighbourhood']],df.price)

LinearRegression()

In [160]:
reg.coef_

array([ 4.01815858e+02, -3.85766283e+02, -1.04993191e+02,  1.66403930e-01,
       -3.31125530e+02,  4.28854792e+02, -1.37951732e+02,  7.22575361e+02,
       -4.85836128e+00,  3.98572002e+02, -1.55796622e-01,  1.65484867e+02,
        3.91644186e+02,  1.33469998e-01, -4.68220966e+02,  2.51839652e+02,
       -1.26739742e-01])

In [161]:
reg.intercept_

6015.82902531041

In [162]:
y_pred = reg.predict(test_x)

In [163]:
y_pred

array([15873.65524652,  9891.89841697,  7421.66743269, ...,
       34554.0652657 , 20921.01332223, 19081.01458943])

In [164]:
reg.predict([[1,0,0,1474,2,2,4,0,17,1,0,0,1,19310,0,1,1600]])

array([9640.56163937])

In [165]:
from sklearn.metrics import mean_squared_error

In [166]:
mse = mean_squared_error(test_y, y_pred)

In [167]:
import math

In [168]:
rmse = math.sqrt(mse)

In [169]:
print(rmse)

67181.74525111208


In [176]:
df2 = pd.DataFrame({
    "submission": y_pred
})

df2.to_csv("submission.csv", index=False)

In [177]:
df2

submission
0      15873.655247
1       9891.898417
2       7421.667433
3      27254.909731
4      23539.649026
...             ...
57717  17975.711450
57718   8758.567615
57719  34554.065266
57720  20921.013322
57721  19081.014589

[57722 rows x 1 columns]